#!/bin/bash
_MSG=`date "+%y%m%d-%H%M"`
_HOST=`hostname -s`
_CMSG=$@

git add . && git commit -m "$_HOST:$_MSG:$_CMSG"
git push git@gitjoe:joelee-kr/pyHello.git
#
#git push       git@gitjoe:joelee-kr/pyHello.git main
#git push -u -f git@gitjoe:joelee-kr/pyHello.git main
# JOELEE JOELEE
